# Generated by Django 3.1.1 on 2020-09-10 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='insurance',
            field=models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_id', to='Policy.businesspartner'),
        ),
    ]
