# Generated by Django 3.1.1 on 2020-09-11 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0004_auto_20200910_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role_id': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_id', to='Policy.businesspartner'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='insurance',
            field=models.ForeignKey(default=1, limit_choices_to={'role_id': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_id', to='Policy.businesspartner'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_holder',
            field=models.ForeignKey(limit_choices_to={'role_id': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='holder_id', to='Policy.businesspartner'),
        ),
    ]
