# Generated by Django 3.1.1 on 2020-09-11 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0005_auto_20200911_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerrole',
            name='role_name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='partnertype',
            name='type_name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='agent',
            field=models.ForeignKey(default=1, limit_choices_to={'role_id': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_id', to='Policy.businesspartner'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_holder',
            field=models.ForeignKey(default=1, limit_choices_to={'role_id': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='holder_id', to='Policy.businesspartner'),
        ),
        migrations.AlterField(
            model_name='policystatus',
            name='status_name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='policytransactiontype',
            name='transaction_type',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
