# Generated by Django 3.1.1 on 2020-09-11 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0006_auto_20200911_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='bp_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Policy.partnertype'),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Policy.partnerrole'),
        ),
        migrations.AlterField(
            model_name='partnerrole',
            name='role_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnertype',
            name='type_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Policy.policystatus'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Policy.policytransactiontype'),
        ),
        migrations.AlterField(
            model_name='policystatus',
            name='status_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policytransactiontype',
            name='transaction_type',
            field=models.CharField(max_length=255),
        ),
    ]
