# Generated by Django 3.1.1 on 2020-09-11 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0008_auto_20200911_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='bp_Type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Policy.partnertype'),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Policy.partnerrole'),
        ),
    ]
