# Generated by Django 3.1.1 on 2020-09-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0009_auto_20200912_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspartner',
            old_name='bp_Type',
            new_name='bp_Type_id',
        ),
        migrations.RenameField(
            model_name='businesspartner',
            old_name='role',
            new_name='role_id',
        ),
    ]
