# Generated by Django 3.1.1 on 2020-09-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0011_auto_20200912_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effective_date',
            field=models.DateField(),
        ),
    ]
