# Generated by Django 3.1.1 on 2020-09-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0012_auto_20200912_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='period_of_cover',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
